<?xml version="1.0" encoding="UTF-8"?><testrun name="ChatClientManagerTest" project="rmi-chat-client" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="chatclient.ChatClientManagerTest" time="1.411">
    <testcase name="isExistingUserTest_Success" classname="chatclient.ChatClientManagerTest" time="1.411">
      <error>java.rmi.ConnectException: Connection refused to host: 159.107.166.144; nested exception is: 
	java.net.ConnectException: Connection refused: connect&#13;
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)&#13;
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)&#13;
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)&#13;
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:341)&#13;
	at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)&#13;
	at chatclient.ChatClientManagerTest.isExistingUserTest_Success(ChatClientManagerTest.java:38)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:606)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.net.ConnectException: Connection refused: connect&#13;
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)&#13;
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)&#13;
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)&#13;
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)&#13;
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)&#13;
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)&#13;
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)&#13;
	at java.net.Socket.connect(Socket.java:579)&#13;
	at java.net.Socket.connect(Socket.java:528)&#13;
	at java.net.Socket.&lt;init&gt;(Socket.java:425)&#13;
	at java.net.Socket.&lt;init&gt;(Socket.java:208)&#13;
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)&#13;
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:147)&#13;
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)&#13;
	... 29 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
